spring:
  application:
    name: spring-cloud-alibaba-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"